require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe PersonesController do

  # This should return the minimal set of attributes required to create a valid
  # Persone. As you add validations to Persone, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "first_name" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # PersonesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all persones as @persones" do
      persone = Persone.create! valid_attributes
      get :index, {}, valid_session
      assigns(:persones).should eq([persone])
    end
  end

  describe "GET show" do
    it "assigns the requested persone as @persone" do
      persone = Persone.create! valid_attributes
      get :show, {:id => persone.to_param}, valid_session
      assigns(:persone).should eq(persone)
    end
  end

  describe "GET new" do
    it "assigns a new persone as @persone" do
      get :new, {}, valid_session
      assigns(:persone).should be_a_new(Persone)
    end
  end

  describe "GET edit" do
    it "assigns the requested persone as @persone" do
      persone = Persone.create! valid_attributes
      get :edit, {:id => persone.to_param}, valid_session
      assigns(:persone).should eq(persone)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Persone" do
        expect {
          post :create, {:persone => valid_attributes}, valid_session
        }.to change(Persone, :count).by(1)
      end

      it "assigns a newly created persone as @persone" do
        post :create, {:persone => valid_attributes}, valid_session
        assigns(:persone).should be_a(Persone)
        assigns(:persone).should be_persisted
      end

      it "redirects to the created persone" do
        post :create, {:persone => valid_attributes}, valid_session
        response.should redirect_to(Persone.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved persone as @persone" do
        # Trigger the behavior that occurs when invalid params are submitted
        Persone.any_instance.stub(:save).and_return(false)
        post :create, {:persone => { "first_name" => "invalid value" }}, valid_session
        assigns(:persone).should be_a_new(Persone)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Persone.any_instance.stub(:save).and_return(false)
        post :create, {:persone => { "first_name" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested persone" do
        persone = Persone.create! valid_attributes
        # Assuming there are no other persones in the database, this
        # specifies that the Persone created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Persone.any_instance.should_receive(:update_attributes).with({ "first_name" => "MyString" })
        put :update, {:id => persone.to_param, :persone => { "first_name" => "MyString" }}, valid_session
      end

      it "assigns the requested persone as @persone" do
        persone = Persone.create! valid_attributes
        put :update, {:id => persone.to_param, :persone => valid_attributes}, valid_session
        assigns(:persone).should eq(persone)
      end

      it "redirects to the persone" do
        persone = Persone.create! valid_attributes
        put :update, {:id => persone.to_param, :persone => valid_attributes}, valid_session
        response.should redirect_to(persone)
      end
    end

    describe "with invalid params" do
      it "assigns the persone as @persone" do
        persone = Persone.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Persone.any_instance.stub(:save).and_return(false)
        put :update, {:id => persone.to_param, :persone => { "first_name" => "invalid value" }}, valid_session
        assigns(:persone).should eq(persone)
      end

      it "re-renders the 'edit' template" do
        persone = Persone.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Persone.any_instance.stub(:save).and_return(false)
        put :update, {:id => persone.to_param, :persone => { "first_name" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested persone" do
      persone = Persone.create! valid_attributes
      expect {
        delete :destroy, {:id => persone.to_param}, valid_session
      }.to change(Persone, :count).by(-1)
    end

    it "redirects to the persones list" do
      persone = Persone.create! valid_attributes
      delete :destroy, {:id => persone.to_param}, valid_session
      response.should redirect_to(persones_url)
    end
  end

end
